### ISSUE TITLE
Invalidation fails with `Unknown output type: eu-west-1`

### ISSUE THREAD

**Issue by joanvila** [chetan/invalidate-cloudfront-action#14]
Hi team I know this issue has been raised before but I could not figure it out. When running the CloudFront invalidation with this config:

```
- name: Invalidate CloudFront
   uses: chetan/invalidate-cloudfront-action@master
   env:
       AWS_REGION: 'eu-west-1'
       AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
       DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
       PATHS: '/*'
```

I'm getting the error `Unknown output type: eu-west-1`.

It is worth noting that the invalidation works fine on the path `/*` as it can be seen in the AWS UI. It's just that the action fails.

It should not be a permissions issue since the AWS user has full CloudFront permissions.

I've tried setting the `DEBUG: "1"` flag but doesn't give any further information.

If it helps, I'm running this action in a monorepo. But I don't think it has anything to do with it since the action does not interact with the project files.

Any help would be appreciated.
