### ISSUE TITLE
Unknown output type

### ISSUE THREAD

**Issue by ctvw** [chetan/invalidate-cloudfront-action#15]
Receiving this error.

Run chetan/invalidate-cloudfront-action@v2
Run $GITHUB_ACTION_PATH/entrypoint.sh
Unknown output type: us-east-1
Error: Process completed with exit code 255.

```
name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./website/ s3://ctvw.xyz --delete

    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: "/index.html"
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

**Comment by chetan** [comment]
@ctvw can you try running it again with the DEBUG flag? Your config looks ok, however you shouldn't need the AWS access/secret configs, since you are already using the configure action above and it will provide those values.

```yaml
    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DEBUG: "1"
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: "/index.html"
        AWS_REGION: "us-east-1"
```
