### ISSUE TITLE
An error occurred (ServiceUnavailable) when calling the CreateInvalidation operation

### ISSUE THREAD

**Issue by jonbhanson** [chetan/invalidate-cloudfront-action#18]
Thanks for creating this great action, it eases our deployment!

Today when deploying I received this error:

> ```
> An error occurred (ServiceUnavailable) when calling the CreateInvalidation operation (reached max retries: 4): CloudFront encountered an internal error. Please try again.
> ```

[This stack overflow answer](https://stackoverflow.com/a/73829744/8371825) suggests increasing the number of retries.  Is this a configurable option?

**Comment by chetan** [comment]
@jonbhanson you should be able to simply add it to the job env like so:

```yaml
- name: invalidate
  uses: chetan/invalidate-cloudfront-action@v2
  env:
    PATHS_FROM: .updated_files
    AWS_REGION: 'us-east-1'
    DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_MAX_ATTEMPTS: 10
```
