### ISSUE TITLE
Error when creating the invalidation

### ISSUE THREAD

**Issue by yarooob** [chetan/invalidate-cloudfront-action#3]
Hi there,
I am trying to use the action but I am getting the following error every time I run the action:
```
Unknown output type: us-east-2
##[error]Docker run failed with exit code 255
```

my workflow file contains the following:
```
on:
  push:
    branches:
      - TestingCICD

jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Deploying the app
    steps:
      - name: Checkout..
        uses: actions/checkout@v1
      - name: using the setup-node action to build node environment in the machine...
        uses: actions/setup-node@v1
        with:
          node-version: '12.10.0'
      - name: installing the packages
        run: npm install
      - name: building the project and generating the binary file
        run: npm run generate
      - name: uploading the build to the s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env: #the env vars of this step
         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: 'us-east-2'  #  optional: defaults to us-east-1
         SOURCE_DIR: 'dist'      # optional: defaults to entire repository

         #clearing the cloudfront cache
      - name: invalidate Cloudfront (clearing the cache)
        uses: chetan/invalidate-cloudfront-action@master
        env:
         DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
         PATHS: '/'
         AWS_REGION: 'us-east-2'
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
However, when I check the cloudfront invalidations list, I find a new item being added. but I want to solve the issue
any help will be appreciated.
