### ISSUE TITLE
Invalidation PATHS Environment Variable Stopped Working

### ISSUE THREAD

**Issue by ghost** [chetan/invalidate-cloudfront-action#5]
In my yaml I'm including `PATHS: '/*'` in the env:

```
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

This worked on my invalidations up through Jan 11, 2020:

![image](https://user-images.githubusercontent.com/56774006/72367848-ec103400-36ca-11ea-92c3-2f234d76770e.png)

Now my invalidations look like the following, which seems to be ignoring the `PATHS` env:

![image](https://user-images.githubusercontent.com/56774006/72367965-2548a400-36cb-11ea-9323-725907cffc27.png)
