### ISSUE TITLE
Invalidation fails with error message: Unknown output type: us-east-1

### ISSUE THREAD

**Issue by jgcrunden** [chetan/invalidate-cloudfront-action#8]
My config for the Invalidate Cloudfront Action is:
```
   - name: Invalidate CloudFront Cache
     uses: chetan/invalidate-cloudfront-action@master
     env:
       DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
       PATHS: '/index.html'
       AWS_REGION: 'us-east-1'
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
Although the invalidation is triggered and is successful within AWS, the GH Action returns:
```
Unknown output type: us-east-1
```
And fails.
It sounds like the `aws configure` command run earlier in bash script is setting the region value as the output value (rather than "text").
I've tried running that part of your bash script on my machine to see if I can replicate the problem but haven't had any luck.
I'm completely stumped by this...
Any ideas would be greatly appreciated. :)

Many thanks
Joshua
